[package]
name = "spectre"
version = "0.2.0"
edition = "2021"
authors = ["niklaslong <niklas@long.ch>"]
description = "A lightweight toolkit for analysing p2p network topologies."
license = "MIT"
repository = "https://github.com/niklaslong/spectre"
documentation = "https://docs.rs/spectre"
readme = "README.md"
categories = ["algorithms"]
keywords = ["p2p", "peer-to-peer", "networking"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crepe = "0.1"
nalgebra = "0.30.1"
